### ISSUE TITLE
Helium app version 2.2.1 on Ledger Live

### ISSUE THREAD

**Issue by lsimon305** [helium/helium-ledger-cli#11]
Hello,

Looks like Ledger live has a 2.2.1 version of the Helium app, and now running the helium ledger cli command from my mac I receive 

request error

I'm using this version (helium-ledger-cli-v2.1.1-x86-64-macos) which worked BEFORE upgrading the helium app in Ledger Live, so I'm assuming I need to wait for the 2.2.1 version of the helium cli app?

**Comment by alexwtz** [comment]
Same problem on my side 
using helium on ledger v2.2.1
and helium-ledger-cli-v2.1.2-x86-64-macos on my macbook air (m1)

**Comment by OronSubayi** [comment]
I'm new to Helium and just got a Ledger Nano X
Have the same issue when testing by checking the balance

helium-ledger-cli 2.1.2 on Windows 10
The ledger itself is asking to confirm the address but the CLI already has the "request error"

The Ledger Live app is v2.2.1 as well

**Comment by lthiery** [comment]
@lsimon305 @alexwtz @OronSubayi 
Apologies for not noticing this issue sooner!

Ledger CLI version 2.1.3 is a critical update so that HTTP Requests can work again.

Let me know if you are still having issues after adopting the newest release.

**Comment by OutsideSeth** [comment]
I am seeing the same issue with a Ledger Nano X on Ledger CLI version v2.1.3 and Ledger Live app v2.2.1

**Comment by lthiery** [comment]
@OutsideSeth could you please copy-paste the entire command and error message here?

**Comment by OutsideSeth** [comment]
![Helium CLI Wallet - Error](https://user-images.githubusercontent.com/93942507/150285982-4bb22952-b27f-40fa-b67b-364c11c60472.jpg)

**Comment by danielpdo** [comment]
Hello everyone, are you still experiencing this issue? 
I'm getting the following message when I try to check my helium balance:
Communicating with Ledger - follow prompts on screen
error: Error getting version. App must be waiting for a command.
192:helium-ledger-app-1.1.2-x86_64-apple-darwin 

Does this issue has been solved? Thanks!

**Comment by slphelan** [comment]
I am not able to input commands in the cli using macbook pro does show the following but unable to put in any commands:
Last login: Thu Mar 24 18:30:53 on ttys000
slphelan@Sams-MacBook-Pro ~ % /Users/slphelan/Downloads/helium-ledger-cli-v2.1.3-x86-64-macos/helium-ledger-cli ; exit;
Communicating with Ledger - follow prompts on screen
helium-ledger-cli 2.1.3
Interact with Ledger Nano S for hardware wallet management

USAGE:
    helium-ledger-cli [OPTIONS] <SUBCOMMAND>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
        --account <account>      Select account index to stake from [default: 0]
        --emulator <emulator>    Enable interaction with emulator for development and testing by configuring port for
                                 TCP connection here (typically 9999 or 40000)

SUBCOMMANDS:
    balance       Get wallet information
    burn          Burn to given address
    help          Prints this message or the help of the given subcommand(s)
    pay           Pay a given address
    validators    Stake a validator

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by sysfu** [comment]
environment:
elementary OS 6.1 Jólnir (Ubuntu 20.04.3 LTS)
Helium ledger app 2.2.1
helium-ledger-cli 2.1.3

balance requests work, but all pay commands fail with "Helium API Error" message

**Comment by sysfu** [comment]
Tried the same transaction on macOS using helium-ledger-app 1.1.2 and it worked.

**Comment by nunofgs** [comment]
I'm completely stuck. @sysfu how were you able to downgrade the ledger app?

**Comment by slphelan** [comment]
Did not downgrade had to update to the new one

On May 10, 2022, at 5:45 AM, Nuno Sousa ***@***.******@***.***>> wrote:



I'm completely stuck. @sysfu<https://github.com/sysfu> how were you able to downgrade the ledger app?

**Comment by lthiery** [comment]
I think this issue is now resolved. Please open if there are still pending issues relating to this ticket.
