### ISSUE TITLE
Support form macOS Homebrew package manager

### ISSUE THREAD

**Issue by msnelling** [helium/helium-ledger-cli#14]
Could you please add the `helium-ledger-cli` tool to the macOS Homebrew package manager? https://docs.brew.sh/

**Comment by lthiery** [comment]
I'm not a mac user so I wouldn't feel particularly comfortable managing/testing distributing through homebrew. If somebody from the community wanted to take that up, that'd be totally fine, IMO. However, we're also hoping to get integrated in LedgerLive in the coming months, so I think usefulness of the CLI being more easily accessible via Homebrew will be less. Will you still use the CLI when the same features are available via Ledger Live?

**Comment by timrosenbach** [comment]
I've created a [tap](https://github.com/timrosenbach/homebrew-helium-ledger-cli/) for the Ledger CLI.

Feel free to fork/clone it to a helium based repository. Just be sure to name it helium/homebrew-<what you want> and it should work out of the box for version 2.2.3. For future version there would be a change needed every time or some logic that changes the file when a new release is done.
