### ISSUE TITLE
error getting version

### ISSUE THREAD

**Issue by crschu0** [helium/helium-ledger-cli#20]
I am using a Nano S Plus.  and when I try to check my balance I get this message:
"C:\Users\crsch>helium-ledger-cli balance
Communicating with Ledger - follow prompts on screen
error: Error getting version: Data length is wrong with 3 bytes. Your ledger application may require an update."

version in use on device is 2.2.4
version installed to windows is 2.2.4-alpha.0
Nano S Plus version is 1.0.3

Thanks for your help

CS

**Comment by gdutk007** [comment]
I was getting the same issue on my Windows desktop, but I rebuilt the application from source and the problem went away on my nano x

**Comment by crschu0** [comment]
Thank you.  I ended up installing the previous version and things went well

**Comment by lthiery** [comment]
Sorry about that. Please avoid using alpha releases as they are for testing upcoming releases of the Helium app on Ledger.
