### ISSUE TITLE
Error getting version: Data length is wrong with 3 bytes on v2.2.4-alpha.0

### ISSUE THREAD

**Issue by kellybyrd** [helium/helium-ledger-cli#22]
Several users in Helium's Discord are reporting this error when running v2.2.4-alpha0 and the latest (as of 2022-08-01) version of the HNT app on the Ledger device. Search the discord for "Data length is wrong with 3 bytes"

**Comment by kellybyrd** [comment]
A user in discord reported that after downgrading to v2.2.3 of this cli app, the error was gone.

**Comment by lthiery** [comment]
The 2.2.4-alpha is not meant for general use yet, which is why it was tagged as alpha.
