### ISSUE TITLE
APDU Payload Error companion app sent wrong size

### ISSUE THREAD

**Issue by fintechtrades** [helium/helium-ledger-cli#25]
Hello, I have HNT stored on my Ledger Nano X.

When using the helium-ledger-cli, I am getting the error APDU Payload Error companion app sent wrong size 

This happens when trying to create a pay transaction.

Helium Ledger App Version - 2.2.4

I have tried using different versions of helium-ledger-cli but still getting the same error. I tried downloading the Helium Wallet App for Android, but it's not detecting the Ledger for some reason. Plugged in via cable or bluetooth.

My funds are currently stuck, any help would be appreciated.

**Comment by abhay** [comment]
v2.2.4 is not a tagged release. it's an alpha. please try v2.2.3

**Comment by fintechtrades** [comment]
> v2.2.4 is not a tagged release. it's an alpha. please try v2.2.3

I have tried multiple different versions of helium-ledger-cli, all delivering the same error. 

My meaning was on the Ledger Nano X, the the Helium version is 2.2.4

**Comment by abhay** [comment]
you should see something like this... 
```
% ./helium-ledger-cli balance              
Communicating with Ledger - follow prompts on screen
Ledger running Helium App v2.2.4

helium-ledger/2.2.3
```

```
% ./helium-ledger-cli --version
Communicating with Ledger - follow prompts on screen
helium-ledger 2.2.3
```
cc: @lthiery if he has any other advice.

**Comment by fintechtrades** [comment]
> you should see something like this...
> 
> ```
> % ./helium-ledger-cli balance              
> Communicating with Ledger - follow prompts on screen
> Ledger running Helium App v2.2.4
> 
> helium-ledger/2.2.3
> ```
> 
> ```
> % ./helium-ledger-cli --version
> Communicating with Ledger - follow prompts on screen
> helium-ledger 2.2.3
> ```
> 
> cc: @lthiery if he has any other advice.

Yes, when I do helium-ledger-cli balance, it shows that. And this command works.

When I do helium-ledger-cli pay xx 100, the error shows on the Ledger Nano X device itself, unable to approve the send.

**Comment by lthiery** [comment]
What operating system are you on? The wrong amount of bytes are being received by the Ledger which is a very low-level error.

**Comment by fintechtrades** [comment]
> What operating system are you on? The wrong amount of bytes are being received by the Ledger which is a very low-level error.

Using Macbook Pro M2. 

Let me try it using Windows

**Comment by lthiery** [comment]
Do give that a shot. If you're running M2, it might be some weird emulation bug as I don't think we have a native release for M1/M2 yet.

**Comment by fintechtrades** [comment]
> Do give that a shot. If you're running M2, it might be some weird emulation bug as I don't think we have a native release for M1/M2 yet.

Using a Windows PC works fine, thank you for the suggestion!

ty @abhay also
