### ISSUE TITLE
CLI won't show balance "request error"

### ISSUE THREAD

**Issue by shahmat** [helium/helium-ledger-cli#26]
When I run this from command line:

`./helium-ledger-cli balance`

It says: "request error" under the balance column

> Communicating with Ledger - follow prompts on screen
> Ledger running Helium App v2.2.4
> 
> helium-ledger/2.2.3

**Comment by lthiery** [comment]
@shahmat could you try again? this call makes a few sequential API calls and sometimes the API refuses it.

**Comment by shahmat** [comment]
@lthiery I've tried it many times, also with the v2.2.4 alpha software but that was erroring out.  

When I run the command the ledger prompts me to "confirm address" but at that point the CLI has already displayed "request error"

**Comment by lthiery** [comment]
@shahmat API is actually under maintenance right now. Try again in a few hours.

**Comment by shahmat** [comment]
@lthiery Thanks for replying, it is still saying "request error", not sure what to do

**Comment by samuelvanderwaal** [comment]
I solved this by building 2.2.3 from source and using that with my Ledger.
