### ISSUE TITLE
Helium API Error request error

### ISSUE THREAD

**Issue by warning0810** [helium/helium-ledger-cli#29]
Hi , after migration i can`t move my HNT from ledger to other wallet.
Every time when i use pay command send me this error:Helium API Error request error
I have 2300HNT on my ledger,can someone help me with this?
Thanks

**Comment by lthiery** [comment]
@warning0810 please refer to the migration documentation 
https://docs.helium.com/solana/migration/ledger/

**Comment by jgrossmac** [comment]
So is the TLDR that we are waiting on a pending release to migrate HNT over?

**Comment by lthiery** [comment]
@jgrossmac no - migration has been available since day 1 of the Solana migration.

https://docs.helium.com/solana/migration/ledger/
