### ISSUE TITLE
RE: Wallet/CLI - Nano S Firmware supported list - Is Nano S Firmware 2.0.0 supported with the experimental Helium Wallet?

### ISSUE THREAD

**Issue by trstaub** [helium/helium-ledger-cli#3]
In brief: Is Nano S Firmware 2.0.0 supported with the experimental Helium Wallet?

Any updates on support for Nano X?

I have a Ledger Nano S with Firmware 1.6.1 and was about to upgrade to Firmware 2.0.0.
As I was going through my mental checks before doing firmware updates, I wondered if it would break Helium support as an experimental app.

Is there is list of firmware versions required and supported?  I don't see it here easily in the Wiki or the Docs wallet instructions.

Is Nano S Firmware 2.0.0 supported with the experimental Helium Wallet?

**Comment by lthiery** [comment]
Yes, Firmware 2.0.0 is supported with the recent release.
