### ISSUE TITLE
Can't access helium tokens address after migration

### ISSUE THREAD

**Issue by adiruss** [helium/helium-ledger-cli#30]
Hello, since I can no longer access the tokens using helium-ledger-cli, I tried to access the new address generated on the Solana blockchain using Solflare and Phantom. The problem is that I cannot access the address where the tokens are located using my device , it doesn't appear in any list. I managed to find the address where the tokens are using this documentation https://docs.helium.com/solana/migration/exchange/. My question is, how was it possible for the coins to transfer to an address that I cannot access using  my ledger device?

**Comment by lthiery** [comment]
Did you follow the instructions here? https://docs.helium.com/solana/migration/ledger

The new address is valid for a transitory Helium-Solana app and the migration helps you move the tokens to a standard Solana app.

**Comment by adiruss** [comment]
Yes, I used the migration tool. I've now resolved the issue , it turns out that I was selecting a different address at step 1, which wasn't correlated with the address where the tokens were located, which is why nothing was happening. Thank you for your response and assistance. Good luck with your future endeavors!
