### ISSUE TITLE
staking command fails with 'Upgrade the Helium Ledger App to use validator commands'

### ISSUE THREAD

**Issue by mishawagon** [helium/helium-ledger-cli#4]
Hi Community,
When I try to stake using the command: 
`./helium-ledger-cli validator stake 10000 ACTUALADDRESS`
I get this strange error:
```
thread 'main' panicked at 'Upgrade the Helium Ledger App to use validator commands', src/txns/validator/mod.rs:25:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
My ledger app is already v1.0.0, don't see any newer ones via Ledger Live interface. Any thoughts would be greatly appreciated.

**Comment by woodlandsquash** [comment]
> Hi Community,
> When I try to stake using the command:
> `./helium-ledger-cli validator stake 10000 ACTUALADDRESS`
> I get this strange error:
> 
> ```
> thread 'main' panicked at 'Upgrade the Helium Ledger App to use validator commands', src/txns/validator/mod.rs:25:13
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```
> 
> My ledger app is already v1.0.0, don't see any newer ones via Ledger Live interface. Any thoughts would be greatly appreciated.


You have to update your Ledger firmware and then update the Helium App Firmware to the latest version

**Comment by mishawagon** [comment]
> > Hi Community,
> > When I try to stake using the command:
> > `./helium-ledger-cli validator stake 10000 ACTUALADDRESS`
> > I get this strange error:
> > ```
> > thread 'main' panicked at 'Upgrade the Helium Ledger App to use validator commands', src/txns/validator/mod.rs:25:13
> > note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > My ledger app is already v1.0.0, don't see any newer ones via Ledger Live interface. Any thoughts would be greatly appreciated.
> 
> You have to update your Ledger firmware and then update the Helium App Firmware to the latest version

You are right, thank you very much!
