### ISSUE TITLE
Cannot view balance

### ISSUE THREAD

**Issue by mattpont** [helium/helium-ledger-cli#6]
Hello,

Using v2.1.0 on my Mac. I also get the exact same error on Windows 10.

When I use the following command to get the wallet balance:
"./helium-ledger-cli balance"

I get the following:
"error: Error getting version. App must be waiting for a command."

Thanks!

**Comment by lthiery** [comment]
Hi @mattpont !

Sorry for the very late response. I missed this Issue when it was first posted.

This usually means you did not start the Helium App and click through the "Pending Ledger Review" warning.

Let me know if you still are having issues.
