### ISSUE TITLE
Error accessing Ledger HID Device, Ledger Live Already Closed

### ISSUE THREAD

**Issue by taoteh1221** [helium/helium-ledger-cli#7]
Hello.

Here is a bug report using latest nano s firmware and ledger live helium app, with helium-ledger-cli for linux. It is not functional on Ubuntu v20.04.

Device: Ledger Nano S (firmware v2.0.0)

Operating System: Ubuntu v20.04 (ledger udev rules added: https://github.com/LedgerHQ/udev-rules)

Step to reproduce: Helium app installed in developer mode, ledger live shut down, unplug / plug back in Nano S and open Helium app:

![IMG_20211017_171106977](https://user-images.githubusercontent.com/1760489/137645468-063af3a3-0b9f-4976-843c-a0f62d2067e8.jpg)

Run ./helium-ledger-cli balance

`taoteh1221@ubuntu:~/Apps/helium-ledger-cli$ ./helium-ledger-cli balance`
`Communicating with Ledger - follow prompts on screen`
`error: Error accessing Ledger HID Device. Be sure that Ledger Live is not running.`
`taoteh1221@ubuntu:~/Apps/helium-ledger-cli$ `

We already shut down ledger live, and restarted the nano s, so this is not due to ledger live being open. I'm presuming this is a bug, so reporting it here. Any ideas on a workaround for now on linux ubuntu would be appreciated?

Thanks,
Mike

**Comment by lthiery** [comment]
Hi @taoteh1221 !

I'm sorry I missed this when you first posted.

You need to click past the warning to be able to interact with the app.

Let me know if you are still having issues!
